# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test02WaitElements():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_02WaitElements(self):
    self.driver.get("https://www.saucedemo.com//")
    self.driver.set_window_size(1295, 687)
    self.driver.find_element(By.LINK_TEXT, "Modal").click()
    self.driver.find_element(By.ID, "modal-button").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "close-button").click()
  
